# Generated by Django 5.1.2 on 2024-10-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_subscriber_alter_quote_from_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='other1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='other2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
