version: "3.8"
services:
  db:
    image: postgres:15.3
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5432:5432"
    command: postgres
    networks:
      - tsbvans-nw
    env_file:
      - ./.env
    expose:
      - 5432
  
volumes:
  postgres_data:

